sudo: required
dist: xenial
language: python
python:
- '3.6'
services:
- mysql
env:
  global:
  - secure: nnswvWrevd1UmoWuqAYqbUPg75b/HXvM9k5kY0CMN/1k5qAk/9Ydiok5HEXa7BEryh29fmkPUcjaTcWifFdvSXs0lrvFZ5qAWRXYbXRSlyBMpnJbBNeI/90TwstW3p5+qddj+HeaEDlQy5Ku00uuOaKqPWUF2LIRS8yw1wbh2yXmE8sCjvbKq11Pu0jPdIi4BuGmbRyZ8B9MrumGPBrJUOQ61olmCuFGrhKMwddgFO4vDkfjk694YP8/ekDzFoUySz2cmSBDJhyWJ5UDXjlbvJa3hQBdMHBwXypmqH90D9xkKyi7xNUr5euBIUkNutBY6TeHAX5of6+lZnNXk2BtfCjBlfEdOpP1k/b9OIQJD6xJctKzbMNC5pslPt0u7V8Wqs2vN9XPX7jyCMsB3NWQbvpEVFkaFCrKdM0Azs8SZA5FXAIL81jtexWQv3nVhJ0A2P/o7PBj3GoSeLRKvXPytIwcoUKm2g7JBAJGktMSmd0sF9HhSK1gTkv2zOEvy3mMumMHYL0fSPqZEe+YWcp8dTquhf3i2Cxq0eZpbfh0vaufKGg9HPrS2udRMJizfMV/VhE2UsX7lq9MyBbHzjI4rUzOuUf966iFigpHCxhtr5Z9Mu/VnqaXlinOP111I09Dbnia/NFOmSkXuo6iaCrrYu3c7DBfieWKx9Hz3xipbUE=
  - secure: U9LWxV0zz2zk33op33ZCQMC0u7rath+7812N8WL/6bIpNv77ARb/VeP8NBqDqSoBi1nwvo/WHhCUIEUpKQn4yKIw/5CFCbdTlXppQYNUjS8//IdvaL9nfRkbxGIi1TUR4yWcAYhH6bzMUQQfjZMde1Oet6FzrTpBBg3rWhFRnu9Ju6ca35Nh97WiTAvuulO935grk9PCFxOMfck3vSeflO6MUwWL65pQgVlR+mLadkjzDsIqiS2Y4a00sBT68xppn3tMIEh3ke6c8rj5hnEmEfoY5METsMiQeVU6E8n+nRsQHCAgwizBLK1Q8gRbarIEhz8wM44cDTSz0vcMuqlJGA2QtCIB2i+OqySooNgDHO7A6Hf47013HmqzZ93HoBXMGgpL1NmZwFJzsSoOd9RjXZGreTy3i+tcSelQXLkFHwzfuaXKr8cnohamsxVpE9VRkize30pVN3OkxnX22FdJoSoy1kH3TI/VJ8Lzy8KSqmPFmxgYZpapIp+rGg2UcE08uLsu09YyCunGK0/Vh9n/U61AWz2dp74tlXu5ekx+ypxpr9rax3t/uFNLNobxXYiecs3M8MCV5zYnOFyPkCwBPjUPLGZ1k0J2MlYfhvGgrEhVEuvsj1fUkwIpjl43wTQhnse/C5Myd0amsF2g2gwreJ/lmEv55WdpnU8JOKvSxdA=

before_install:
# - mysql -u root --password="" < setup_db_and_test_user.sql
# TODO Set up user in database
- echo 'DB_HOST=127.0.0.1' > .env
- echo 'DB_USER=root' > .env
- echo 'DB_PASS=""' > .env
- echo 'DB_NAME=playlists' > .env
- echo $SPOTIFY_CLIENT_ID > .env
- echo $SPOTIFY_CLIENT_SECRET > .env
install:
- pip install -r requirements.txt
script: make test
